DROP TABLE IF EXISTS cameras;
DROP TABLE IF EXISTS drivers;
DROP TABLE IF EXISTS trucks;
DROP TABLE IF EXISTS vendors;
DROP TABLE IF EXISTS materials;
ALTER TABLE users DROP CONSTRAINT IF EXISTS fk_users_customer;
DROP TABLE IF EXISTS customers;
